add_newline = false

format = "$all"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[character]
success_symbol = "[â¯](#89b8c2)"

[cmd_duration]
disabled = true

[directory]
truncation_length = 100
truncation_to_repo = false
style = "bold #89b8c2"

[git_branch]
style = "#84a0c6"

[git_commit]
format = "[($hash)]($style) [($tag)]($style)"

[git_status]
style = "#b4be82"

[username]
style_user = "bold #89b8c2"
style_roog = "bold red"
